//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by "LoadSceneMenuFileGenerator".
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEditor;
using UnityEditor.SceneManagement;

namespace Assets.Editor
{
    public static class LoadSceneMenu_Generated
    {
        [MenuItem("SceneLoading/Load Scene/Room/Load EastCorridor")]
        public static void LoadScene_0()
        {
            string relativeScenePath = @"Assets/Scenes/EastCorridor.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/Room/Load EastGenerator")]
        public static void LoadScene_1()
        {
            string relativeScenePath = @"Assets/Scenes/EastGenerator.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/MainScene/Load EndGameScreen")]
        public static void LoadScene_2()
        {
            string relativeScenePath = @"Assets/Scenes/EndGameScreen.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/Room/Load Entrance")]
        public static void LoadScene_3()
        {
            string relativeScenePath = @"Assets/Scenes/Entrance.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/Room/Load Lab")]
        public static void LoadScene_4()
        {
            string relativeScenePath = @"Assets/Scenes/Lab.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/Room/Load LabAccess")]
        public static void LoadScene_5()
        {
            string relativeScenePath = @"Assets/Scenes/LabAccess.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/Gameplay/Load 0-Gameplay")]
        public static void LoadScene_6()
        {
            string relativeScenePath = @"Assets/Scenes/0-Gameplay.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/MainScene/Load MainMenuScreen")]
        public static void LoadScene_7()
        {
            string relativeScenePath = @"Assets/Scenes/MainMenuScreen.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/MainScene/Load MasterScene")]
        public static void LoadScene_8()
        {
            string relativeScenePath = @"Assets/Scenes/MasterScene.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/Room/Load OpenSpace")]
        public static void LoadScene_9()
        {
            string relativeScenePath = @"Assets/Scenes/OpenSpace.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/Room/Load WestCorridor")]
        public static void LoadScene_10()
        {
            string relativeScenePath = @"Assets/Scenes/WestCorridor.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		[MenuItem("SceneLoading/Load Scene/Room/Load WestGenerator")]
        public static void LoadScene_11()
        {
            string relativeScenePath = @"Assets/Scenes/WestGenerator.unity";
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                EditorSceneManager.OpenScene(relativeScenePath, OpenSceneMode.Additive);
            }
        }
		
    }
}